Cxx17 updates
OpenTimelineIO/OpenTimelineIO-C-Bindings pull request #58
Opened 2024-03-31 07:05 UTC by rogergodspeed

This matches the c++17 branch changes to OpenTimelineIO. Specifically replacing the custom any class with std::any and optional with std::optional.

NOTE: The json version schema feature has NOT been ported and instead the new schema_version_map has been hardcoded to an empty map.

2024-03-31 07:06 UTC, rogergodspeed commented
@meshula Should please double check it is ok to update this without supporting the json schema_version_map.

2024-04-05 01:42 UTC, meshula commented
@rogergodspeed It's fine to defer that until everything else is working....

2024-04-14 20:10 UTC, meshula requested changes
Can you make a note in the README.md about the work remaining? Specifically the version map support. I'm happy to land this, with a breadcrumb about the outstanding work remaining so that no one is surprised. I don't think anyone is dependent on managing the versioning system from C at the moment, so deferring it is OK.

2024-04-15 22:04 UTC, meshula approved these changes

2024-04-15 22:06 UTC, merged